### PR TITLE
Jc generalize accumulate

### PR DESCRIPTION
**Pull request by JaredCrean2**
Implements ideas discussed in #159.  I targeted `develop`, is that the right branch?

### CODE REVIEW

**Comment by JaredCrean2** [comment]
I'm not sure why all these NightlyBot commits are there.  This might need a rebase.

**Comment by JaredCrean2** [comment]
I rebased on `develop`, but that didn't remove the excess commits.

**Comment by tobinw** [comment]
You could try squashing those commits.

**Comment by cwsmith** [comment]
I'm guessing your initial branch was created from `master` instead of `develop`.  I rebased this on `SCOREC/develop` and squashed the commits to create the following patch.  
[jc_accumulate.patch.gz](https://github.com/SCOREC/core/files/2237528/jc_accumulate.patch.gz)

If the patch looks good to you please run the following commands on your forks `jc_generalize_accumulate` branch (or a different branch if you want to preserve it):

```
git checkout <some working branch>
git reset --hard origin/develop
git am jc_accumulate.patch #after unzipping it
```

Once that all looks good you can force push to your fork and this PR will update itself.

**Comment by JaredCrean2** [comment]
Created a new pull request: #161

**Pull request closed without merging**
