### PR TITLE
Add support for reading 2D ugrid files

### PR DESCRIPTION
**Pull request by tuckerbabcock**
This PR addresses #281 and extends `apf::loadMdsFromUgrid` to support reading 2D ugrid meshes. It sets the parametric values of mesh vertices for 2D meshes by inverse evaluating the geometric model at the coordinates of the vertex, if the `gmi` model supports the inverse evaluation.

**NOTE**: I've used C++11 features in the code that sets vertex parametric coordinates (the developer guide doesn't specify what maximum standard should be used).

### CODE REVIEW

**Comment by cwsmith** [comment]
@tuckerbabcock Thank you.  

Do you have a 2d ugrid file we can add to our nightly test meshes repo?

This can be tested by passing a 2d ugrid mesh file into the [from_ugrid](https://github.com/SCOREC/core/blob/70374171728094f4db7081b1b420205fc65b7d38/test/ugrid.cc) driver/utility?

**Comment by tuckerbabcock** [comment]
@cwsmith yes I can add one, how should I add it? Does the mesh need to have a model associated with it?

**Comment by cwsmith** [comment]
Thank you.  

I sent you an invite to 'collaborate' on the pumi-meshes repo.  

We currently have a 3d mesh in the `fun3d` dir.
https://github.com/SCOREC/pumi-meshes/tree/6d1601a29152e2043b16b2522c1a346b877920a0/fun3d

It probably makes sense to rename that directory `ugrid` and add the 2d mesh there.  In `core` we'll need to modify `test/testing.cmake` accordingly.

If you want to make the directory name change and upload the 2d mesh I will make the changes to `testing.cmake`.

**Comment by tuckerbabcock** [comment]
I renamed that directory and added the 2D mesh.

**Pull request merged**
