### PR TITLE
Jc copy data

### PR DESCRIPTION
**Pull request by JaredCrean2**
This change adds an optional argument to `apf::convert` (and functions that call `apf::convert`) that controls whether Fields/Numberings/GlobalNumberings/Tags are copied.  The default value is true, to preserve the original behavior.

This behavior is useful for doing an in-memory copy of the mesh data structure only.

### CODE REVIEW

**Comment by JaredCrean2** [comment]
Fixed base branch and merged with recent changes

**Comment by JaredCrean2** [comment]
@cwsmith When you get a chance, can you review this PR?

**Comment by JaredCrean2** [comment]
I'm not sure how, because the most recent commit is a merge commit, so it doesn't show up with `git rebase -i'.  Is there another way of doing it?

**Comment by cwsmith** [comment]
OK.  So it looks like you had to manually merge 6cc556e7ae4131e2ede0d53c48605a36ee9ed91c (or later) with your changes. Git rerere may have been able to resolve this without the merge commit, but I'm not sure:
https://git-scm.com/docs/git-rerere

**Pull request merged**
