### PR TITLE
Add release build to github workflow

### PR DESCRIPTION
**Pull request by jacobmerson**
## Adding release build to GitHub actions

see issue #358 . The current release build fails, but the GitHub actions tests are passing. To make sure we notice these issues cropping up I have (attempted) to add a release build to the GitHub actions workflow.

### CODE REVIEW

**Comment by jacobmerson** [comment]
It turns out the release build wasn't the only issue causing my build to fail. That being said, we should probably be testing that both the debug and release builds work since `bob.cmake` inserts a bunch of flags depending on build type and most developers don't bother to check if code is compiling with multiple build types.

**Comment by jacobmerson** [comment]
To replicate the errors I was seeing I updated ubuntu to use `ubuntu-latest` which will use more modern compilers which tends to catch more issues.

Ultimately, the -Werror flag should not be in the release build as discussed in #316

**Comment by cwsmith** [comment]
@jacobmerson This looks good.  Thank you.  Are you all set with this?

**Comment by jacobmerson** [comment]
The pipeline works and I'm set with that. Do you need me to fix the build errors (existing issues in PUMI) before merge?

**Comment by cwsmith** [comment]
Either way (new PR or here) works for me.

**Comment by jacobmerson** [comment]
As I track this down I noticed that the compiler is not getting selected correctly. gcc is used for the clang build as well.

**Comment by jacobmerson** [comment]
@cwsmith we are nearing completion with this and you could probably merge as is (although I should cleanup the commit history). One interesting side effect is that the `field_io` test fails for the gcc release build. This may indicate that there is some undefined behavior lurking that creates a problem with the gcc optimizer. Do you need me to try to track this down before merge?  Hopefully we can replicate with gcc-10 on the SCOREC systems.

If you are happy to merge as is, I will rebase the commits to make them nice.

**Review by cwsmith — APPROVED** [review]
@jacobmerson LGTM.  Thank you. 

Lets merge this and then resolve the `field_io` error in a separate PR.

**Comment by jacobmerson** [comment]
@cwsmith I don't have merge permissions for core. Can you merge when you get a chance? I squashed the commits into something reasonable.

**Pull request merged**
