### PR TITLE
introduce reduceFieldData and ReductionOp

### PR DESCRIPTION
**Pull request by JaredCrean2**
implements #159, this time based on the right branch.

### CODE REVIEW

**Comment by cwsmith** [comment]
This looks good.  Would you please also add a test driver that exercises the various reductions and does some sort of sanity check of the results?

**Comment by JaredCrean2** [comment]
Added a test.  It writes a field and then performs the reduction, and compares against the exact result.  I checked all 3 reduction (sum, min, max).  The first one checks that the original value is multiplied by `n`, and for the other ones I added the MPI rank of the process to the field value and checked that the reduction picked the right one.

**Comment by cwsmith** [comment]
`fieldReduce.cc` is missing.

**Comment by JaredCrean2** [comment]
New pull request #165 .  I ran CTest on one of the workstations, and all tests pass.

**Pull request merged**
