### PR TITLE
Add region classification to apf::deriveMdlFromManifold

### PR DESCRIPTION
**Pull request by zhang-alvin**
PR to add mesh region to model region classification to the 2D/3D functions for deriving a discrete geometry based on mesh entity classifications. 

This is needed for the Proteus project to work correctly with multi-region domains.

Based on how the model is derived, there isn't a clear way to define the bounding surfaces for the model regions or how the regions are separated. I do not know how this will affect mesh adaptation.

### CODE REVIEW

**Comment by zhang-alvin** [comment]
initialClassification
postAdaptClassification

So it looks like some additional classification info will be needed to ensure that new elements have the same region classification as the parents.

**Comment by mortezah** [comment]
> initialClassification
> postAdaptClassification
> 
> So it looks like some additional classification info will be needed to ensure that new elements have the same region classification as the parents.

is this a 2D example?

**Comment by zhang-alvin** [comment]
> > initialClassification
> > postAdaptClassification
> > So it looks like some additional classification info will be needed to ensure that new elements have the same region classification as the parents.
> 
> is this a 2D example?

Yes. Do you have an idea of what might be needed to preserve the region classification in this context?

**Comment by mortezah** [comment]
> > > initialClassification
> > > postAdaptClassification
> > > So it looks like some additional classification info will be needed to ensure that new elements have the same region classification as the parents.
> > 
> > 
> > is this a 2D example?
> 
> Yes. Do you have an idea of what might be needed to preserve the region classification in this context?

Can you have the meshes overlay on each other? I want to see what is the operator causing this.

**Comment by zhang-alvin** [comment]
@mortezah 

overlay_withCoarsen

I've set the initial mesh edges to be colored white whereas the adapted mesh to be colored black. The dark blue patches seem to result from edge swaps and collapses.

**Comment by mortezah** [comment]
> @mortezah
> 
> overlay_withCoarsen
> 
> I've set the initial mesh edges to be colored white whereas the adapted mesh to be colored black. The dark blue patches seem to result from edge swaps and collapses.

That does not seem to be always the case. When you do the adapt can you set in->shouldCoarsen = false, so we now that we only have refinement and swap happening?

**Comment by mortezah** [comment]
One more question. Does this happen for 3D meshes?

**Comment by mortezah** [comment]
One last question. If the new regions (the ones in dark blue in the pictures) are not classified on the correct regions, what are they classified on? Do they even have classifications?

**Comment by zhang-alvin** [comment]
overlay_withNoCoarsen

Overlay with `in->shouldCoarsen=false`. I have not checked with 3D meshes but I suspect similar issues/problems will arise.

**Comment by zhang-alvin** [comment]
> One last question. If the new regions (the ones in dark blue in the pictures) are not classified on the correct regions, what are they classified on? Do they even have classifications?

Good question. This output suggests that were classified on a region with ID 0, although no such region should exist in the original mesh.

**Comment by zhang-alvin** [comment]
@mortezah , let me know if this will be simpler to explain/discuss via a slack call, if you have an idea of what might be happening.

**Comment by mortezah** [comment]
> > One last question. If the new regions (the ones in dark blue in the pictures) are not classified on the correct regions, what are they classified on? Do they even have classifications?
> 
> Good question. This output suggests that were classified on a region with ID 0, although no such region should exist in the original mesh.

So when you define the classifications for a given mesh region to be on a given model region, what do you do for the bounding entities of that region? 

One more thought. Can you maybe try a two-region mesh that is generated with simmetrix (converted to pumi) and some made-up size field and see if the same thing happens after adapt?
I have a 2D mesh/model with 2 regions here https://www.dropbox.com/s/tegx5xh4gnmreey/mesh_model.zip?dl=1

**Comment by zhang-alvin** [comment]
> > > One last question. If the new regions (the ones in dark blue in the pictures) are not classified on the correct regions, what are they classified on? Do they even have classifications?
> > 
> > 
> > Good question. This output suggests that were classified on a region with ID 0, although no such region should exist in the original mesh.
> 
> So when you define the classifications for a given mesh region to be on a given model region, what do you do for the bounding entities of that region?
> 
> One more thought. Can you maybe try a two-region mesh that is generated with simmetrix (converted to pumi) and some made-up size field and see if the same thing happens after adapt?
> I have a 2D mesh/model with 2 regions here https://www.dropbox.com/s/tegx5xh4gnmreey/mesh_model.zip?dl=1

I think the first thought regarding bounding entities of the model region is the likely cause of the issue. As of now, there is no such information being supplied. There is no information being propagated down to lower dimensional entities either, so a vertex in the model region does not have the right classification.

**Comment by mortezah** [comment]
> > > > One last question. If the new regions (the ones in dark blue in the pictures) are not classified on the correct regions, what are they classified on? Do they even have classifications?
> > > 
> > > 
> > > Good question. This output suggests that were classified on a region with ID 0, although no such region should exist in the original mesh.
> > 
> > 
> > So when you define the classifications for a given mesh region to be on a given model region, what do you do for the bounding entities of that region?
> > One more thought. Can you maybe try a two-region mesh that is generated with simmetrix (converted to pumi) and some made-up size field and see if the same thing happens after adapt?
> > I have a 2D mesh/model with 2 regions here https://www.dropbox.com/s/tegx5xh4gnmreey/mesh_model.zip?dl=1
> 
> I think the first thought regarding bounding entities of the model region is the likely cause of the issue. As of now, there is no such information being supplied. There is no information being propagated down to lower dimensional entities either, so a vertex in the model region does not have the right classification.

That is also my suspicion. In general, any mesh entity has to have a __unique__ classification. More specifically, each mesh entity has to be classified on the lowest possible dimension model entity. In other words, if M<sub>i</sub><sup>d<sub>i</sub></sup> is classified on G<sub>j</sub><sup>d<sub>j</sub></sup> then d<sub>i</sub> <= d<sub>j</sub>

**Comment by zhang-alvin** [comment]
Okay, I think I'll be able to classify the "interior" vertices with the appropriate region classification. This won't resolve the missing bounding entities for the regions.

Is it possible to bound a model region in the following manner: 
Classification

Currently, the derived model function creates model edges that need not be contiguous. So is it reasonable to bound region 0 with edges {10,5,1}.

**Comment by mortezah** [comment]
> Okay, I think I'll be able to classify the "interior" vertices with the appropriate region classification. This won't resolve the missing bounding entities for the regions.
> 
> Is it possible to bound a model region in the following manner:
> Classification
> 
> Currently, the derived model function creates model edges that need not be contiguous. So is it reasonable to bound region 0 with edges {10,5,1}.

A proper model would never look like the one you have shown in the picture. That being said, you might be able to do that (i.e., bounding model region 0 with edges 10, 5, 1) and get the mesh adapt to work, but note that there is going to be a problem if you ever have a mesh edge that connects the top and bottom model edges (the ones shown as edge 5 in your picture).

Also, I don't think that is the issue for the swaps failing to classify things properly (at least for the swaps that are happening away from any boundary). For a mesh region that is completely inside a given model region (i.e., no intersection with any boundary of the model) one needs to classify that mesh region an all of its downward entities (in your 2D example verts and edges) on the same model region. That should fix the problem with interior swaps.  The ones on the boundary are a bit trickier.

**Comment by zhang-alvin** [comment]
> > Okay, I think I'll be able to classify the "interior" vertices with the appropriate region classification. This won't resolve the missing bounding entities for the regions.
> > Is it possible to bound a model region in the following manner:
> > Classification
> > Currently, the derived model function creates model edges that need not be contiguous. So is it reasonable to bound region 0 with edges {10,5,1}.
> 
> A proper model would never look like the one you have shown in the picture. That being said, you might be able to do that (i.e., bounding model region 0 with edges 10, 5, 1) and get the mesh adapt to work, but note that there are going to be a problem. For example, if you ever have a mesh edge that connects the top and bottom model edges (the ones shown as edge 5 in your picture).
> 
> Also, I don't think that is the issue for the swaps failing to classify things properly (at least for the swaps that are happening away from any boundary). For a mesh region that is completely inside a given model region (i.e., no intersection with any boundary of the model) one needs to classify that mesh region an all of its downward entities (in your 2D example verts and edges) on the same model region. That should fix the problem with interior swaps. The ones on the boundary are a bit trickier.

Yes this was never really meant to be a fully functioning model. This started off primarily as a hack to get Proteus working with adaptivity since there isn't a proper way to generate a model. We're actually looking into the Capstone workflow, so that might be the long-term solution. I'll try the downward classifications to resolve the swap issue.

**Comment by zhang-alvin** [comment]
Going to close this for now since it doesn't since adding downward classification in 3D isn't sufficient to avoid errors.

**Pull request closed without merging**
