### PR TITLE
System Tests

### PR DESCRIPTION
**Pull request by Angelyr**
Added Github Action tests for Perlmutter and Frontier

### CODE REVIEW

**Comment by jacobmerson** [comment]
Are the target endpoint ids supposed to be secret or those are fine to publish?

**Comment by Angelyr** [comment]
@jacobmerson You need an authentication token to connect to the endpoint, so it is safe to publish the endpoint.

**Review by jacobmerson — APPROVED** [review]

**Review by cwsmith — APPROVED** [review]

**Comment by cwsmith** [comment]
@Angelyr Would you please rebase your branch on `develop` ?

**Review by cwsmith — CHANGES_REQUESTED** [review]
Would you please rebase your branch on `develop` ?

**Comment by Angelyr** [comment]
@cwsmith I have rebased the branch

**Review by cwsmith — APPROVED** [review]
Thank you.

**Comment by Angelyr** [comment]
Cam you merge the branch for me?

**Pull request merged**
