### PR TITLE
Jc generalize accumulate2

### PR DESCRIPTION
**Pull request by JaredCrean2**
Fixed handling of ghosts.

### CODE REVIEW

**Comment by cwsmith** [comment]
I resolved the merge conflicts and then built on pachisi with gcc 7.3 and mpich 3.2.1 (see [this page](https://wiki.scorec.rpi.edu/wiki/Redhat_environment) for redhat7 info).

The following build error appears:

```bash
[  5%] Building CXX object apf/CMakeFiles/apf.dir/apfFieldData.cc.o
/lore/cwsmith/develop/core/apf/apfFieldData.cc: In function âvoid apf::accumulateFieldData(apf::FieldDataOf<double>*, apf::Sharing*, bool)â:
/lore/cwsmith/develop/core/apf/apfFieldData.cc:108:23: error: âreduce_opâ was not declared in this scope
           values[i] = reduce_op.getNeutralElement();
                       ^~~~~~~~~
/lore/cwsmith/develop/core/apf/apfFieldData.cc:108:23: note: suggested alternative: âReductionOpâ
           values[i] = reduce_op.getNeutralElement();
                       ^~~~~~~~~
                       ReductionOp
make[2]: *** [apf/CMakeFiles/apf.dir/apfFieldData.cc.o] Error 1
```

**Comment by JaredCrean2** [comment]
That is unexpected.  Can you push the commit where the merge conflicts are resolved to this branch (it appears I don't have access to pachisi)?

**Comment by cwsmith** [comment]
@JaredCrean2 can you access this directory:

/lore/cwsmith/develop/core

It currently has the 'mergeJaredAcc' branch checked out.  I'm not sure how to list just the changes I made in the conflict resolution... I'm guessing there is a way ([I did not have rerere on](https://hackernoon.com/fix-conflicts-only-once-with-git-rerere-7d116b2cec67)).

**Comment by JaredCrean2** [comment]
Added the missing file, and clones the pull request branch to a new repository and ran the tests, just to make sure.

**Pull request merged**
